### ISSUE TITLE
Refactor todo list

### ISSUE THREAD

**Issue by jlchan** [jlchan/JuliaDG#4]
ESDG: 
- [x] Nodal/modal ESDG solvers
- [ ] ALE-WADG solver
- [ ] DG Jacobian matrices
- [ ] Dimensional transforms/fluxes for compressible Euler/NS
- [ ] BCs for compressible NS
- [ ] IDP limiter (DIffEq SSP schemes + stage limiter)
- [x] Better visualization (Makie + https://github.com/pazner/TriplotRecipes.jl?)

StartUpDG:
- [ ] Tet support

Longer-term: 
- [ ] implicit solvers
- [ ] iterative solvers + precon
